export const PERMISSION = {
    READ: "READ",
    WRITE: "WRITE",
    DELETE: "DELETE",
    SHARE: "SHARE",
    UPLOAD_FILE: "UPLOAD_FILE"
}


export const PERMISSION_ALLOWED = [PERMISSION.READ, PERMISSION.WRITE, PERMISSION.DELETE, PERMISSION.SHARE, PERMISSION.UPLOAD_FILE]
